name: Test Suite # IMPORTANT: If this name changes you need to update the canceller.yml

# Controls when the action will run.
on:
  # Triggers the workflow on push for the master branch.
  push:
    branches: [ develop, master ]

  # Triggers the workflow on pull request for any branch.
  pull_request:

  # Allows you to run this workflow manually from the Actions tab.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.4, 3.5, 3.6, 3.7 ]
    steps:
      # Checks-out the  repository.
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests
        run: python tests.py
